Landing Page Complete
Star-Academy/Fall1402-TwoWeek-InternShip-Frontend pull request #1
Opened 2023-11-22 12:36 UTC by FarahaniMehrshad

2023-11-22 16:09 UTC, milar7 requested changes
ممکنه بعضی موارد چون تکراری بود همش رو کامنت نگذاشته باشم. همه رو سعی کنید درست کنید.

2023-11-22 16:09 UTC, milar7 commented on src/styles.css
> +  --dark-white: #b1b1b1;
از hsl استفاده کنید بجای hex. هر جا دیگه هم هست تغییر بدید. بقیه جاها نقطه (.) میزارم یعنی مثل این کامنت رو قبلا گفتم

2023-11-22 16:09 UTC, milar7 commented on src/styles.css
> +  background: linear-gradient(180deg, #d0368a 0%, #708ad4 99%);
.

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +}*/
remove comments

2023-11-22 16:09 UTC, milar7 commented on src/styles.css
> +}
توصیه میشه واسه تجربه بهتر کاربری هیچ وقت اسکرولبار رو تغییر ندید. یسری دلایل داره مثلا اینکه داخل همه مروگر ها یکسان نیست دیگه. الان همینی که زدید داخل firefox اعمال نمیشه

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.html
> +    <img src="./assets/images/icon.png" alt="game store logo" class="logo grey-background">
بهتره واسه عکس ها از فرمت 
webP 
که واسه وب بهینه شده استفاده کنید.
از این سایت میتونید کمک بگیرید
https://squoosh.app/

https://star-academy.github.io/codestar-documents/docs/frontend/phase02-pilot#%D8%B9%DA%A9%D8%B3%D9%87%D8%A7

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +  margin-top: 0.5rem;
توصیه میشه از 
margin 
استفاده نکنید. بجاش به پدرش 
padding
بدید

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +  margin-left: 1rem;
از 
margin 
که استفاده نکنید،
به جای
left or right
هم از
Logical Properties
استفاده کنید.
لینک:
https://star-academy.github.io/codestar-documents/docs/frontend/phase06-clean-code#logical-properties

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +  color: white;
hsl

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +  border-top: 0.3rem solid white;
.

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +  background-color: white;
.

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +  background-color: rgba(177, 177, 177, 0.5);
.

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +  background: linear-gradient(to right, #f96595, #974c75);
.

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +  margin-bottom: 1rem;
.

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +  margin-top: 0.2rem;
.

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +  margin-right: 2rem;
x margin
use Logical Properties

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +  color: white;
hsl

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +.bottom-header{
اسم بهتر ^_^

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +}
بجای این به پدرش 
justify-content: space-between
بدید

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +}
اینو من بدون
devTools
نتونستم ببینمش.
یا رنگ بهتر یا حذف بشه

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +}
به
main
display: flex; flex-direction:column; gap:5rem;
بدین
و این 
margin-topها
رو پاک کنید

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +#header, #main {
پس 
footer
چی؟

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +  margin-top: 1rem;
در واقع میخواستن این مورد پاینن ترین قسمت کارت باشه
img,h3,p
رو بندازید داخل یه 
div
بعد به 
li 
justify-content : space-between 
بدین

2023-11-22 16:09 UTC, milar7 commented on src/app/app.component.css
> +  margin-right: 0.2rem;
به جای این به 
a
اینو بدین
display: flex;
justify-content: center;
align-items: center;
gap: 0.2rem;

2023-11-22 16:50 UTC, alirrah commented on src/styles.css
> +  --dark-white: #b1b1b1;
تغییر داده شد.

2023-11-22 16:50 UTC, alirrah commented on src/styles.css
> +  background: linear-gradient(180deg, #d0368a 0%, #708ad4 99%);
تغییر داده شد

2023-11-22 16:52 UTC, alirrah commented on src/app/app.component.css
> +}*/
پاک شد

2023-11-22 16:54 UTC, alirrah commented on src/styles.css
> +}
حذف شد

2023-11-22 16:58 UTC, alirrah commented on src/app/app.component.css
> +  color: white;
تغییر داده شد

2023-11-22 16:59 UTC, alirrah commented on src/app/app.component.css
> +  color: white;
تغییر داده شد

2023-11-22 17:09 UTC, alirrah commented on src/app/app.component.css
> +  border-top: 0.3rem solid white;
تغییر داده شد

2023-11-22 17:10 UTC, alirrah commented on src/app/app.component.css
> +  background-color: white;
تغییر داده شد

2023-11-22 17:11 UTC, alirrah commented on src/app/app.component.css
> +  background-color: rgba(177, 177, 177, 0.5);
تغییر داده شد

2023-11-22 17:11 UTC, alirrah commented on src/app/app.component.css
> +  background: linear-gradient(to right, #f96595, #974c75);
تغییر داده شد

2023-11-22 17:11 UTC, alirrah commented on src/app/app.component.css
> +  margin-bottom: 1rem;
تغییر داده شد

2023-11-22 17:12 UTC, alirrah commented on src/app/app.component.css
> +}*/
حذف شد

2023-11-23 05:43 UTC, alirrah commented on src/app/app.component.html
> +    <img src="./assets/images/icon.png" alt="game store logo" class="logo grey-background">
فرمت عکس ها تغییر پیدا کرد

2023-11-23 06:42 UTC, alirrah commented on src/app/app.component.css
> +  margin-top: 0.5rem;
اصلاح شد

2023-11-23 06:42 UTC, alirrah commented on src/app/app.component.css
> +  margin-left: 1rem;
اصلاح شد

2023-11-23 06:42 UTC, alirrah commented on src/app/app.component.css
> +  margin-bottom: 1rem;
تغییر داده شد

2023-11-23 06:43 UTC, alirrah commented on src/app/app.component.css
> +  margin-top: 0.2rem;
اصلاح شد

2023-11-23 06:43 UTC, alirrah commented on src/app/app.component.css
> +  margin-right: 2rem;
اصلاح شد

2023-11-23 06:49 UTC, alirrah commented on src/app/app.component.css
> +.bottom-header{
top-header با upper-part
bottom-header با lower-part
جایگزین شد

2023-11-23 06:49 UTC, alirrah commented on src/app/app.component.css
> +}
اصلاح شد

2023-11-23 06:54 UTC, alirrah commented on src/app/app.component.css
> +}*/
حذف شد

2023-11-23 06:55 UTC, alirrah commented on src/app/app.component.css
> +}
حذف شد

2023-11-23 06:55 UTC, alirrah commented on src/app/app.component.css
> +}
اصلاح شد

2023-11-23 07:07 UTC, alirrah commented on src/app/app.component.css
> +#header, #main {
اضافه شد

2023-11-23 07:07 UTC, alirrah commented on src/app/app.component.css
> +  margin-top: 1rem;
اصلاح شد

2023-11-23 07:21 UTC, alirrah commented on src/app/app.component.css
> +}*/
اصلاح شد و vertical-align ها حذف شد

2023-11-23 07:21 UTC, alirrah commented on src/app/app.component.css
> +  margin-right: 0.2rem;
اصلاح شد و vertical-align ها حذف شد

2023-11-23 07:48 UTC, milar7 approved these changes

2023-11-23 08:19 UTC, merged