Refactor to angular
Star-Academy/Fall1402-TwoWeek-InternShip-Frontend pull request #2
Opened 2023-11-30 12:05 UTC by FarahaniMehrshad

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer-menu/footer-menu.component.ts
> +  @Input() items!: {link: string, text: string}[];
بهتر است از مقدار دیفالت استفاده شود

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer-phone/footer-phone.component.html
> +  <li *ngFor="let item of items">
trackBy انجام بدید

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer-menu/footer-menu.component.ts
> +  @Input() items!: {link: string, text: string}[];
از اینترفیس استفاده شود

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer-phone/footer-phone.component.ts
> +  @Input() items!: string[];
مقدار دهی اولیه

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer-social/footer-social.component.html
> +  <li *ngFor="let item of items">
trackBy

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer-social/footer-social.component.html
> +    <a href="{{item.link}}">
[href]='item.link'

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer-social/footer-social.component.html
> +      <i class="{{item.icon}}"></i>
[class]="item.icon"
درمورد ngclass و ngStyle بخونید و ببینید فرقش چیه با کلاس

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer-social/footer-social.component.scss
> +    align-items: center;
فاصله

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer-social/footer-social.component.scss
> +    border-radius: 50%;
فاصله

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer-social/footer-social.component.scss
> +
ترتیب رو کلن درست کنید و اینکه فاصله  بدید بین پروپرتی هایی که از یک نوع نیستند 
هرجا دیگه دیدم اینو میگم "نمیگم"

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer-social/footer-social.component.ts
> +  @Input() items!: {link: string, icon: string}[];
interface and default value

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer/footer.component.html
> +      <app-footer-phone [items]="['09547856957', '09684523697']"></app-footer-phone>
بهتر است مقادیر ها داخل یک متغیر ریخته شود و آن پاس داده شود

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer/footer.component.html
> +      <app-footer-menu [items]="[
همینطور این

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer/footer.component.html
> +      <app-footer-social [items]="[
و این

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer/footer.component.scss
> +  background-color: $dark-purple;
نمیگم

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer/footer.component.scss
> +    padding: 0.5rem;
نمیگم

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer/footer.component.scss
> +    font-size: 2.4rem;
نمیگم

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer/footer.component.scss
> +    font-size: 1.2rem;
نمیگم

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/footer/footer.component.scss
> +    background: $gradient;
نمیگم

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/lower-header/lower-header.component.html
> +      <li *ngFor="let item of menu" [ngClass]="{'active' : item.active}">
اگه تغییر میکنه trackBy بزنید

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/lower-header/lower-header.component.scss
> +@use "./../../../styles/variables" as *;
نمیگم

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/lower-header/lower-header.component.scss
> +        *::before {
چرا * ? چرا & نه ؟

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/lower-header/lower-header.component.ts
> +  @Input() public menu: { name: string, active: boolean }[] = [];
interface3

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/components/upper-header/upper-header.component.scss
> +@use "./../../../styles/mixin" as *;
نمیگم

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner-button/banner-button.component.html
> +  <a [routerLink]="[item.link]" class="flex align-center {{item.style}}">
چرا آرایه ؟

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner-button/banner-button.component.scss
> +@use "./../../../../../styles/variables" as *;
نمیگم

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner-button/banner-button.component.ts
> +  @Input() item!: {style: string, text: string, link: string};
interface

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner-button/banner-button.component.ts
> +  @Input() item!: {style: string, text: string, link: string};
default value

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner-item/banner-item.component.html
> +    <li *ngFor="let item of items">
trackBy

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner-item/banner-item.component.scss
> +@use "./../../../../../styles/mixin" as *;
نمیگم

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner-item/banner-item.component.scss
> +  p:first-child {
p {
 &:first-child {
 &:last-child {
 }
 use nested css

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner-item/banner-item.component.ts
> + @Input() items: {icon: string, title: string, description: string}[] = [];
interface

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner/banner.component.html
> +    <app-banner-item [items]="[
use variable

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner/banner.component.html
> +      <app-banner-button [item]="{style: '', text: 'دیگر خریدها', link: '/shop'}"></app-banner-button>
use variable

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner/banner.component.html
> +      <app-banner-button [item]="{style: 'gradient-background', text: 'خرید آیتم های بازی', link: '/shop'}"></app-banner-button>
use variable

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner/banner.component.html
> +<section class="banner">
create interface

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner/banner.component.scss
> +@use "./../../../../../styles/mixin" as *;
نمیگم

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/offer-game/offer-game.component.html
> +      <li *ngFor="let item of items">
trackBy ?

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/offer-game/offer-game.component.html
> +          <img ngSrc={{item.image}} alt="call of duty banner" width="230" height="306.66">
306.66 ????! bruh

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/offer-game/offer-game.component.scss
> +@use "./../../../../../styles/mixin" as *;
نمیگم

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/offer-game/offer-game.component.scss
> +    *:is(button.right, button.left) {
&

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/offer-game/offer-game.component.ts
> +  @Input() items!: {image: string, title: string, description: string, oldPrice: string, price: string}[];
interface and default value

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/popular-game/popular-game.component.html
> +      <img ngSrc={{item.image}} alt="pubg banner" width="106" height="116">
[ngSrc]="item.image"

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/popular-game/popular-game.component.html
> +    <li *ngFor="let item of items">
trackBy

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/popular-game/popular-game.component.scss
> +@use "./../../../../../styles/variables" as *;
نمیگم

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/popular-game/popular-game.component.ts
> +  @Input() items!: { image: string, title: string, description: string, link: string }[];
interface and default value

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/landing.component.html
> +  <app-popular-game [items]="[
use variables

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/landing.component.html
> +  <app-offer-game [items]="[
use variables

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/landing.component.scss
> +@use "../../../styles/mixin" as *;
نمیگم

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/landing.component.ts
> +import {Component} from '@angular/core';
interface

2023-11-30 14:57 UTC, SaveAsArTaZ commented on src/styles.scss
> +/* You can add global styles to this file, and also import other style files */
نمیگم

2023-12-03 08:23 UTC, alirrah commented on src/app/components/footer-menu/footer-menu.component.ts
> +  @Input() items!: {link: string, text: string}[];
مقدار اولیه بهش داده شد

2023-12-03 08:24 UTC, alirrah commented on src/app/components/footer-menu/footer-menu.component.ts
> +  @Input() items!: {link: string, text: string}[];
مقدار اولیه بهش داده شد

2023-12-03 08:24 UTC, alirrah commented on src/app/components/footer-phone/footer-phone.component.ts
> +  @Input() items!: string[];
مقدار اولیه بهش داده شد

2023-12-03 08:24 UTC, alirrah commented on src/app/components/footer-social/footer-social.component.ts
> +  @Input() items!: {link: string, icon: string}[];
مقدار اولیه بهش داده شد

2023-12-03 08:25 UTC, alirrah commented on src/app/components/footer/footer.component.html
> +      <app-footer-phone [items]="['09547856957', '09684523697']"></app-footer-phone>
یک متغییر تعغریف کردم و داخلش مقادیر را ریختم

2023-12-03 08:25 UTC, alirrah commented on src/app/components/footer/footer.component.html
> +      <app-footer-menu [items]="[
یک متغییر تعغریف کردم و داخلش مقادیر را ریختم

2023-12-03 08:25 UTC, alirrah commented on src/app/components/footer/footer.component.html
> +      <app-footer-social [items]="[
یک متغییر تعغریف کردم و داخلش مقادیر را ریختم

2023-12-03 08:26 UTC, alirrah commented on src/app/pages/landing/component/banner-button/banner-button.component.ts
> +  @Input() item!: {style: string, text: string, link: string};
مقدار اولیه بهش داده شد

2023-12-03 08:26 UTC, alirrah commented on src/app/pages/landing/component/banner-button/banner-button.component.ts
> +  @Input() item!: {style: string, text: string, link: string};
مقدار اولیه بهش داده شد

2023-12-03 08:27 UTC, alirrah commented on src/app/pages/landing/component/banner/banner.component.html
> +    <app-banner-item [items]="[
یک متغییر تعریف کردم و داخلش مقادیر را ریختم

2023-12-03 08:27 UTC, alirrah commented on src/app/pages/landing/component/banner/banner.component.html
> +      <app-banner-button [item]="{style: '', text: 'دیگر خریدها', link: '/shop'}"></app-banner-button>
یک متغییر تعریف کردم و داخلش مقادیر را ریختم

2023-12-03 08:27 UTC, alirrah commented on src/app/pages/landing/component/banner/banner.component.html
> +      <app-banner-button [item]="{style: 'gradient-background', text: 'خرید آیتم های بازی', link: '/shop'}"></app-banner-button>
یک متغییر تعریف کردم و داخلش مقادیر را ریختم

2023-12-03 08:28 UTC, alirrah commented on src/app/pages/landing/component/offer-game/offer-game.component.ts
> +  @Input() items!: {image: string, title: string, description: string, oldPrice: string, price: string}[];
مقدار اولیه بهش داده شد

2023-12-03 08:28 UTC, alirrah commented on src/app/pages/landing/component/popular-game/popular-game.component.ts
> +  @Input() items!: { image: string, title: string, description: string, link: string }[];
مقدار اولیه بهش داده شد

2023-12-03 08:28 UTC, alirrah commented on src/app/pages/landing/landing.component.html
> +  <app-popular-game [items]="[
یک متغییر تعریف کردم و داخلش مقادیر را ریختم

2023-12-03 08:28 UTC, alirrah commented on src/app/pages/landing/landing.component.html
> +  <app-offer-game [items]="[
یک متغییر تعریف کردم و داخلش مقادیر را ریختم

2023-12-03 09:09 UTC, alirrah commented on src/app/components/footer-phone/footer-phone.component.html
> +  <li *ngFor="let item of items">
اصلاح شد

2023-12-03 09:09 UTC, alirrah commented on src/app/components/footer-social/footer-social.component.html
> +  <li *ngFor="let item of items">
اصلاح شد

2023-12-03 09:10 UTC, alirrah commented on src/app/components/lower-header/lower-header.component.html
> +      <li *ngFor="let item of menu" [ngClass]="{'active' : item.active}">
اصلاح شد

2023-12-03 09:11 UTC, alirrah commented on src/app/pages/landing/component/banner-item/banner-item.component.html
> +    <li *ngFor="let item of items">
اصلاح شد

2023-12-03 09:11 UTC, alirrah commented on src/app/pages/landing/component/offer-game/offer-game.component.html
> +      <li *ngFor="let item of items">
اصلاح شد

2023-12-03 09:12 UTC, alirrah commented on src/app/pages/landing/component/popular-game/popular-game.component.html
> +    <li *ngFor="let item of items">
اصلاح شد

2023-12-04 07:28 UTC, alirrah commented on src/app/components/footer-menu/footer-menu.component.ts
> +  @Input() items!: {link: string, text: string}[];
اینترفیس تعریف شد

2023-12-04 07:29 UTC, alirrah commented on src/app/components/footer-social/footer-social.component.ts
> +  @Input() items!: {link: string, icon: string}[];
اینترفیس تعریف شد

2023-12-04 07:29 UTC, alirrah commented on src/app/components/lower-header/lower-header.component.ts
> +  @Input() public menu: { name: string, active: boolean }[] = [];
اینترفیس تعریف شد

2023-12-04 07:29 UTC, alirrah commented on src/app/pages/landing/component/banner-button/banner-button.component.ts
> +  @Input() item!: {style: string, text: string, link: string};
اینترفیس تعریف شد

2023-12-04 07:52 UTC, alirrah commented on src/app/components/footer-social/footer-social.component.html
> +    <a href="{{item.link}}">
اصلاح شد

2023-12-04 07:53 UTC, alirrah commented on src/app/components/footer-social/footer-social.component.html
> +      <i class="{{item.icon}}"></i>
اصلاح شد

2023-12-04 09:01 UTC, alirrah commented on src/app/components/footer-menu/footer-menu.component.ts
> +  @Input() items!: {link: string, text: string}[];
اینترفیس براش تعریف شد

2023-12-04 09:02 UTC, alirrah commented on src/app/components/footer-phone/footer-phone.component.ts
> +  @Input() items!: string[];
اینترفیس براش تعریف شد

2023-12-04 09:02 UTC, alirrah commented on src/app/components/footer-social/footer-social.component.scss
> +    align-items: center;
اصلاح کردم

2023-12-04 09:02 UTC, alirrah commented on src/app/components/footer-social/footer-social.component.scss
> +    border-radius: 50%;
اصلاح کردم

2023-12-04 09:02 UTC, alirrah commented on src/app/components/footer-social/footer-social.component.scss
> +
اصلاح کردم

2023-12-04 09:02 UTC, alirrah commented on src/app/components/footer/footer.component.html
> +      <app-footer-phone [items]="['09547856957', '09684523697']"></app-footer-phone>
اینترفیس براش تعریف شد

2023-12-04 09:03 UTC, alirrah commented on src/app/components/footer/footer.component.html
> +      <app-footer-menu [items]="[
اینترفیس براش تعریف شد

2023-12-04 09:03 UTC, alirrah commented on src/app/components/footer/footer.component.html
> +      <app-footer-social [items]="[
اینترفیس براش تعریف شد

2023-12-04 09:03 UTC, alirrah commented on src/app/components/footer/footer.component.scss
> +  background-color: $dark-purple;
اصلاح کردم

2023-12-04 09:03 UTC, alirrah commented on src/app/components/footer/footer.component.scss
> +    padding: 0.5rem;
اصلاح کردم

2023-12-04 09:03 UTC, alirrah commented on src/app/components/footer/footer.component.scss
> +    font-size: 2.4rem;
اصلاح کردم

2023-12-04 09:03 UTC, alirrah commented on src/app/components/footer/footer.component.scss
> +    font-size: 1.2rem;
اصلاح کردم

2023-12-04 09:03 UTC, alirrah commented on src/app/components/footer/footer.component.scss
> +    background: $gradient;
اصلاح کردم

2023-12-04 09:04 UTC, alirrah commented on src/app/components/lower-header/lower-header.component.scss
> +@use "./../../../styles/variables" as *;
اصلاح کردم

2023-12-04 09:04 UTC, alirrah commented on src/app/components/lower-header/lower-header.component.scss
> +        *::before {
اصلاح کردم

2023-12-04 09:04 UTC, alirrah commented on src/app/components/upper-header/upper-header.component.scss
> +@use "./../../../styles/mixin" as *;
اصلاح کردم

2023-12-04 09:04 UTC, alirrah commented on src/app/pages/landing/component/banner-button/banner-button.component.html
> +  <a [routerLink]="[item.link]" class="flex align-center {{item.style}}">
اصلاح کردم

2023-12-04 09:06 UTC, alirrah commented on src/app/pages/landing/component/banner-button/banner-button.component.scss
> +@use "./../../../../../styles/variables" as *;
اصلاح شد

2023-12-04 09:06 UTC, alirrah commented on src/app/pages/landing/component/banner-button/banner-button.component.ts
> +  @Input() item!: {style: string, text: string, link: string};
اینترفیس براش تعریف شد

2023-12-04 09:06 UTC, alirrah commented on src/app/pages/landing/component/banner-item/banner-item.component.scss
> +@use "./../../../../../styles/mixin" as *;
اصلاح کردم

2023-12-04 09:06 UTC, alirrah commented on src/app/pages/landing/component/banner-item/banner-item.component.scss
> +  p:first-child {
اصلاح کردم

2023-12-04 09:07 UTC, alirrah commented on src/app/pages/landing/component/banner-item/banner-item.component.ts
> + @Input() items: {icon: string, title: string, description: string}[] = [];
اینترفیس براش تعریف شد

2023-12-04 09:07 UTC, alirrah commented on src/app/pages/landing/component/banner/banner.component.html
> +    <app-banner-item [items]="[
اینترفیس براش تعریف شد

2023-12-04 09:07 UTC, alirrah commented on src/app/pages/landing/component/banner/banner.component.html
> +      <app-banner-button [item]="{style: '', text: 'دیگر خریدها', link: '/shop'}"></app-banner-button>
اینترفیس براش تعریف شد

2023-12-04 09:07 UTC, alirrah commented on src/app/pages/landing/component/banner/banner.component.html
> +      <app-banner-button [item]="{style: 'gradient-background', text: 'خرید آیتم های بازی', link: '/shop'}"></app-banner-button>
اینترفیس براش تعریف شد

2023-12-04 09:08 UTC, alirrah commented on src/app/pages/landing/component/banner/banner.component.html
> +<section class="banner">
اینترفیس برای همه متغییر ها تعریف شد

2023-12-04 09:08 UTC, alirrah commented on src/app/pages/landing/component/banner/banner.component.scss
> +@use "./../../../../../styles/mixin" as *;
اصلاح شد

2023-12-04 09:10 UTC, alirrah commented on src/app/pages/landing/component/offer-game/offer-game.component.html
> +          <img ngSrc={{item.image}} alt="call of duty banner" width="230" height="306.66">
عدد رو رند کردم

2023-12-04 09:10 UTC, alirrah commented on src/app/pages/landing/component/offer-game/offer-game.component.scss
> +@use "./../../../../../styles/mixin" as *;
اصلاح شد

2023-12-04 09:10 UTC, alirrah commented on src/app/pages/landing/component/offer-game/offer-game.component.scss
> +    *:is(button.right, button.left) {
اصلاح شد

2023-12-04 09:11 UTC, alirrah commented on src/app/pages/landing/component/offer-game/offer-game.component.ts
> +  @Input() items!: {image: string, title: string, description: string, oldPrice: string, price: string}[];
اینترفیس براش تعریف شد

2023-12-04 09:11 UTC, alirrah commented on src/app/pages/landing/component/popular-game/popular-game.component.html
> +      <img ngSrc={{item.image}} alt="pubg banner" width="106" height="116">
اصلاح شد

2023-12-04 09:11 UTC, alirrah commented on src/app/pages/landing/component/popular-game/popular-game.component.scss
> +@use "./../../../../../styles/variables" as *;
اصلاح شد

2023-12-04 09:11 UTC, alirrah commented on src/app/pages/landing/component/popular-game/popular-game.component.ts
> +  @Input() items!: { image: string, title: string, description: string, link: string }[];
اینترفیس براش تعریف شد

2023-12-04 09:11 UTC, alirrah commented on src/app/pages/landing/landing.component.html
> +  <app-popular-game [items]="[
اینترفیس براش تعریف شد

2023-12-04 09:11 UTC, alirrah commented on src/app/pages/landing/landing.component.html
> +  <app-offer-game [items]="[
اینترفیس براش تعریف شد

2023-12-04 09:12 UTC, alirrah commented on src/app/pages/landing/landing.component.scss
> +@use "../../../styles/mixin" as *;
اصلاح شد

2023-12-04 09:12 UTC, alirrah commented on src/app/pages/landing/landing.component.ts
> +import {Component} from '@angular/core';
برای همه متغییر ها اینترفیس تعریف شد

2023-12-04 09:12 UTC, alirrah commented on src/styles.scss
> +/* You can add global styles to this file, and also import other style files */
اصلاح شد

2023-12-05 06:24 UTC, milar7 requested changes

2023-12-05 06:24 UTC, milar7 commented on src/app/app.component.ts
> -//import { RouterOutlet } from '@angular/router';
remove comments

2023-12-05 06:24 UTC, milar7 commented on src/app/app.component.ts
> -  //imports: [CommonModule, RouterOutlet],
remove comments

2023-12-05 06:24 UTC, milar7 commented on src/app/app.component.ts
> -  title = 'gameStore';
public
:string

2023-12-05 06:24 UTC, milar7 commented on src/app/components/footer-menu/footer-menu.component.ts
> +    @Input() items: IMenuItem[] = [];
public

2023-12-05 06:24 UTC, milar7 commented on src/app/components/footer-menu/footer-menu.component.ts
> +    identify(index: number, item: IMenuItem): number {
public

2023-12-05 06:24 UTC, milar7 commented on src/app/components/footer-phone/footer-phone.component.ts
> +        return item.id;
public

2023-12-05 06:24 UTC, milar7 commented on src/app/components/footer-social/footer-social.component.ts
> +}
create a **models** directory and put this in it.

2023-12-05 06:24 UTC, milar7 commented on src/app/components/footer/footer.component.html
> +      <app-footer-social [items]="socialMedia"></app-footer-social>
این سه تا کامپوننت خیلی شبیه هم هستن. اگه css هاشون خیلی فرق نداره میشه یکیشون کرد. اگه نه همین خوبه

2023-12-05 06:24 UTC, milar7 commented on src/app/components/footer/footer.component.ts
> +}
این کار لازم نیست. توضیحش طولانی هست، بیاید تا توضیح بدم

2023-12-05 06:24 UTC, milar7 commented on src/app/components/lower-header/lower-header.component.ts
> +    };
public

2023-12-05 06:24 UTC, milar7 commented on src/app/components/upper-header/upper-header.component.ts
> +interface IMenuItem {
مثل قبلی

2023-12-05 06:24 UTC, milar7 commented on src/app/components/upper-header/upper-header.component.ts
> +    }
publick

2023-12-05 06:24 UTC, milar7 commented on src/app/pages/landing/component/banner-button/banner-button.component.ts
> +    };
```typescript
  @Input() public item: ButtonItem =  {
        link: "";
        style:  "";
        text:  "";
    };
```

2023-12-05 06:24 UTC, milar7 commented on src/app/pages/landing/component/banner-button/banner-button.component.ts
> +}
buttonItemInterface => ButtonItem

2023-12-05 06:24 UTC, milar7 commented on src/app/pages/landing/component/banner-item/banner-item.component.ts
> +    }
public

2023-12-05 06:24 UTC, milar7 commented on src/app/pages/landing/component/banner-item/banner-item.component.ts
> +}
OptionItme
فایل مجزا

2023-12-05 06:24 UTC, milar7 commented on src/app/pages/landing/component/banner/banner.component.ts
> +    ];
چون قرار نیست روش loop بزنید بهتره شکسته بشه به ۳تا property مجزا با اسم مناسب

2023-12-05 06:24 UTC, milar7 commented on src/app/pages/landing/component/offer-game/offer-game.component.ts
> +}
مثل قبلی

2023-12-05 06:24 UTC, milar7 commented on src/app/pages/landing/component/popular-game/popular-game.component.ts
> +}
مثل قبلی

2023-12-05 06:24 UTC, milar7 commented on src/app/pages/landing/landing.component.ts
> +}
مثل قبلی

2023-12-05 06:57 UTC, SaveAsArTaZ requested changes

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/components/footer-menu/footer-menu.component.ts
> +interface IMenuItem {
create a file for interface , do not declare interface in this file

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/components/footer-phone/footer-phone.component.ts
> +    @Input() items: IPhoneItem[] = [];
public

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/components/footer/footer.component.html
> +      <app-footer-social [items]="socialMedia"></app-footer-social>
با میکسین میتونن حتی سی اس اس هاشو جنرال کنند

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/components/footer/footer.component.ts
> +interface IMenuItem {
create a models directory then for each one of these interface create a file and import them

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/components/lower-header/lower-header.component.html
> +                    <i class="fa-solid fa-chevron-down"></i>
this is vanilla approach for using icon in font awesome , learn about how to add icons like adding components

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/components/lower-header/lower-header.component.html
> +            <li *ngFor="let item of menu; trackBy: identify" [ngClass]="{'active' : item.active}">
create a function for ngClass value

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/components/lower-header/lower-header.component.ts
> +interface IMenuItem {
نمیگم

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/components/upper-header/upper-header.component.html
> +      <li *ngFor="let item of menu; trackBy: identify" [ngClass]="{'active' : item.active}">
نمیگم

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner-button/banner-button.component.html
> +  <a [routerLink]="item.link" [class]="item.style">
فرق زیادی نداره ولی برای یک دست شدن پروژه ngClass استفاده کنید

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner-button/banner-button.component.ts
> +    @Input() item: buttonItemInterface = new class implements buttonItemInterface {
public, NEW class ???????? why ?

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner-item/banner-item.component.html
> +            <i [class]="item.icon"></i>
ngClass

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner-item/banner-item.component.ts
> +    @Input() items: optionItemInterface[] = [];
public

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner/banner.component.ts
> +interface optionItemInterface {
نمیگم

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/banner/banner.component.ts
> +class buttonItem implements  buttonItemInterface{
why you created global class ? use interface

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/offer-game/offer-game.component.ts
> +    @Input() items: offerGameItemInterface[] = [];
public

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/component/popular-game/popular-game.component.ts
> +    @Input() items: popularGameItemInterface[] = [];
public

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/landing.component.ts
> +interface IMenuItem {
نمیگم

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/landing.component.ts
> +class popularGameItem implements IPopularGameItem {
همه اینارو میشه از اینترفیس استفاده کرد و مقدار اولیه ای که دادی هم داینامیک نیست یا تعدادشون داینامیک نیست. از اینترفیس استفاده کن جای کلاس

2023-12-05 06:57 UTC, SaveAsArTaZ commented on src/app/pages/landing/landing.component.ts
> +class offerGameItem implements IOfferGameItem {
نمیگم

2023-12-05 07:02 UTC, alirrah commented on src/app/app.component.ts
> -//import { RouterOutlet } from '@angular/router';
حذف شده بودند

2023-12-05 07:02 UTC, alirrah commented on src/app/app.component.ts
> -  //imports: [CommonModule, RouterOutlet],
این مورد هم قبلا اصلاح شده

2023-12-05 07:02 UTC, alirrah commented on src/app/app.component.ts
> -  title = 'gameStore';
کلا حذف شد

2023-12-05 07:03 UTC, alirrah commented on src/app/components/footer-menu/footer-menu.component.ts
> +    @Input() items: IMenuItem[] = [];
اصلاح شد

2023-12-05 07:04 UTC, alirrah commented on src/app/components/footer-menu/footer-menu.component.ts
> +    identify(index: number, item: IMenuItem): number {
اصلاح شد

2023-12-05 07:04 UTC, alirrah commented on src/app/components/footer-phone/footer-phone.component.ts
> +        return item.id;
اصلاح شد

2023-12-05 07:05 UTC, alirrah commented on src/app/components/footer-social/footer-social.component.ts
> +}
فایل مجزا ساخته شد

2023-12-05 07:05 UTC, alirrah commented on src/app/components/footer/footer.component.html
> +      <app-footer-social [items]="socialMedia"></app-footer-social>
ساختار html شون فرق داره
که نمی تونیم یکی کنیم

2023-12-05 07:06 UTC, alirrah commented on src/app/components/footer/footer.component.ts
> +}
اصلاح شد

2023-12-05 07:06 UTC, alirrah commented on src/app/components/lower-header/lower-header.component.ts
> +    };
اصلاح شد

2023-12-05 07:06 UTC, alirrah commented on src/app/components/upper-header/upper-header.component.ts
> +interface IMenuItem {
اصلاح شد

2023-12-05 07:06 UTC, alirrah commented on src/app/components/upper-header/upper-header.component.ts
> +    }
اصلاح شد

2023-12-05 07:08 UTC, alirrah commented on src/app/pages/landing/component/banner-button/banner-button.component.ts
> +    };
اصلاح شد

2023-12-05 07:09 UTC, alirrah commented on src/app/pages/landing/component/banner-button/banner-button.component.ts
> +}
اصلاح شد

2023-12-05 07:09 UTC, alirrah commented on src/app/pages/landing/component/banner-item/banner-item.component.ts
> +    }
اصلاح شد

2023-12-05 07:09 UTC, alirrah commented on src/app/pages/landing/component/banner-item/banner-item.component.ts
> +}
اصلاح شد

2023-12-05 07:10 UTC, alirrah commented on src/app/pages/landing/component/banner/banner.component.ts
> +    ];
روشون loop می زنیم

2023-12-05 07:11 UTC, alirrah commented on src/app/pages/landing/component/offer-game/offer-game.component.ts
> +}
اصلاح شدیم

2023-12-05 07:11 UTC, alirrah commented on src/app/pages/landing/component/popular-game/popular-game.component.ts
> +}
اصلاح شد

2023-12-05 07:11 UTC, alirrah commented on src/app/pages/landing/landing.component.ts
> +}
اصلاح شد

2023-12-05 07:13 UTC, alirrah commented on src/app/components/footer-menu/footer-menu.component.ts
> +interface IMenuItem {
اصلاح شد

2023-12-05 07:14 UTC, alirrah commented on src/app/components/footer-phone/footer-phone.component.ts
> +    @Input() items: IPhoneItem[] = [];
اصلاح شد

2023-12-05 07:14 UTC, alirrah commented on src/app/components/footer/footer.component.ts
> +interface IMenuItem {
اصلاح شد

2023-12-05 07:47 UTC, alirrah commented on src/app/pages/landing/landing.component.ts
> +class offerGameItem implements IOfferGameItem {
اصلاح شد

2023-12-05 07:47 UTC, alirrah commented on src/app/pages/landing/landing.component.ts
> +class popularGameItem implements IPopularGameItem {
اصلاح شد

2023-12-05 07:48 UTC, alirrah commented on src/app/pages/landing/landing.component.ts
> +interface IMenuItem {
اصلاح شد

2023-12-05 07:48 UTC, alirrah commented on src/app/pages/landing/component/popular-game/popular-game.component.ts
> +    @Input() items: popularGameItemInterface[] = [];
اصلاح شد

2023-12-05 07:48 UTC, alirrah commented on src/app/pages/landing/component/offer-game/offer-game.component.ts
> +    @Input() items: offerGameItemInterface[] = [];
اصلاح شد

2023-12-05 07:48 UTC, alirrah commented on src/app/pages/landing/component/banner/banner.component.ts
> +class buttonItem implements  buttonItemInterface{
اصلاح شد

2023-12-05 07:48 UTC, alirrah commented on src/app/pages/landing/component/banner/banner.component.ts
> +interface optionItemInterface {
اصلاح شد

2023-12-05 07:48 UTC, alirrah commented on src/app/pages/landing/component/banner-item/banner-item.component.ts
> +    @Input() items: optionItemInterface[] = [];
اصلاح شد

2023-12-05 09:45 UTC, alirrah commented on src/app/components/lower-header/lower-header.component.html
> +                    <i class="fa-solid fa-chevron-down"></i>
از کامپوننت استفاده کردیم

2023-12-05 09:51 UTC, alirrah commented on src/app/components/lower-header/lower-header.component.html
> +            <li *ngFor="let item of menu; trackBy: identify" [ngClass]="{'active' : item.active}">
اصلاح شد

2023-12-05 09:51 UTC, alirrah commented on src/app/components/lower-header/lower-header.component.ts
> +interface IMenuItem {
اصلاح شد

2023-12-05 09:51 UTC, alirrah commented on src/app/components/upper-header/upper-header.component.html
> +      <li *ngFor="let item of menu; trackBy: identify" [ngClass]="{'active' : item.active}">
اصلاح شد

2023-12-05 09:52 UTC, alirrah commented on src/app/pages/landing/component/banner-button/banner-button.component.html
> +  <a [routerLink]="item.link" [class]="item.style">
از کامپوننت فونت ایکن استفاده کردیم

2023-12-05 09:52 UTC, alirrah commented on src/app/pages/landing/component/banner-button/banner-button.component.ts
> +    @Input() item: buttonItemInterface = new class implements buttonItemInterface {
اصلاح شد

2023-12-05 09:53 UTC, alirrah commented on src/app/pages/landing/component/banner-item/banner-item.component.html
> +            <i [class]="item.icon"></i>
از کامپوننت فونت ایکن استفاده کردیم

2023-12-05 10:55 UTC, milar7 commented on src/app/pages/landing/component/banner/banner.component.ts
> +  ];
تبدیل به obj جدا

2023-12-05 10:56 UTC, milar7 approved these changes

2023-12-05 11:04 UTC, alirrah commented on src/app/pages/landing/component/banner/banner.component.ts
> +  ];
این مورد برای اصلاح دکمه های banner انجام شد

2023-12-05 12:33 UTC, SaveAsArTaZ approved these changes

2023-12-05 14:23 UTC, merged